In [1]:
import pandas as pd
import random
import math
import os

In [2]:
path=os.path.abspath('..')

In [3]:
vote1=pd.read_csv(path+"\\result\\gp_and_bagging.csv")
vote2=pd.read_csv(path+"\\result\\gp_and_bagging_without_description.csv")
vote3=pd.read_csv(path+"\\result\\logistic_des.csv")
vote4=pd.read_csv(path+"\\result\\logistic_mcmc.csv")
vote5=pd.read_csv(path+"\\result\\logistic_nodes.csv")
vote6=pd.read_csv(path+"\\result\\RF_prediction.csv", header=None)
vote7=pd.read_csv(path+"\\result\\xgboost.csv", header=None)
vote8=pd.read_csv(path+"\\result\\xg-without-des.csv", header=None)
vote9=pd.read_csv(path+"\\result\\NB_with_des.csv", header=None)
vote10=pd.read_csv(path+"\\result\\NB_without_des.csv", header=None)
vote11=pd.read_csv(path+"\\result\\logistic_with_des.csv", header=None)
vote12=pd.read_csv(path+"\\result\\logistic_without_des.csv", header=None)

In [4]:
vote1 = vote1.rename(index=str, columns={"gp": "vote1a", "bag": "vote1b"})
vote2 = vote2.rename(index=str, columns={"gp": "vote2a", "bag": "vote2b"})
vote3 = vote3.rename(index=str, columns={"0": "vote3"})
vote4 = vote4.rename(index=str, columns={"0": "vote4"})
vote5 = vote5.rename(index=str, columns={"0": "vote5"})
vote6 = vote6.rename(index=str, columns={"0": "vote6"})
vote7 = vote7.rename(index=str, columns={"0": "vote7"})
vote8 = vote8.rename(index=str, columns={"0": "vote8"})
vote9 = vote9.rename(index=str, columns={"0": "vote9"})
vote10 = vote10.rename(index=str, columns={"0": "vote10"})
vote11 = vote11.rename(index=str, columns={"0": "vote11"})
vote12 = vote12.rename(index=str, columns={"0": "vote12"})

In [5]:
vote3["vote3"] = vote3["vote3"].map( lambda x: x-1 )
vote4["vote4"] = vote4["vote4"].map( lambda x: x-1 )
vote5["vote5"] = vote5["vote5"].map( lambda x: x-1 )

In [6]:
result = pd.concat([vote1, vote2, vote3, vote4, vote5, vote6, vote7, vote8, vote9, vote10, vote11, vote12], axis=1, sort=False)

In [7]:
result

      vote1a  vote1b  vote2a  vote2b  vote3  vote4  vote5  0  0  0  0  0  0  0
0          4       4       4       4      4      4      4  4  4  4  4  4  4  4
1          2       2       2       2      2      2      2  2  2  2  1  2  2  2
2          2       4       4       4      2      2      2  4  3  3  2  2  2  2
3          4       2       4       2      1      1      4  2  2  4  2  4  4  4
4          2       4       2       4      1      1      1  4  1  4  1  1  1  1
5          2       1       2       2      1      1      2  1  2  2  3  3  2  2
6          2       4       2       2      1      1      1  1  2  2  2  2  2  2
7          2       4       4       4      4      4      4  4  4  4  4  4  4  4
8          2       2       2       1      1      1      4  2  4  1  1  1  4  4
9          4       4       4       4      4      4      4  4  4  4  3  3  4  4
10         2       4       4       4      4      4      4  4  4  4  4  4  4  4
11         4       4       4       4      4      4      4  4  4  4  4  4  4  4
12         4       4       4       4      1      1      4  4  4  4  4  4  4  4
13         4       3       4       3      2      2      4  3  3  3  2  2  2  4
14         2       2       2       2      1      1      2  2  2  2  1  1  2  2
15         2       4       2       3      1      1      2  2  2  2  1  1  1  2
16         4       1       4       2      1      1      1  1  1  2  1  1  2  2
17         2       3       2       4      1      1      1  3  3  2  3  3  1  1
18         2       1       2       1      1      1      1  1  1  2  1  1  2  2
19         2       4       2       2      1      1      2  2  2  2  4  4  4  2
20         2       3       2       3      1      1      2  2  2  4  2  2  2  2
21         2       4       2       4      4      4      4  2  4  4  1  2  4  4
22         2       2       4       2      2      2      4  2  2  2  2  2  2  4
23         2       1       4       3      1      1      4  4  4  4  4  4  3  4
24         2       2       2       2      1      1      2  2  2  2  2  2  2  2
25         2       1       2       1      1      1      1  1  1  1  1  1  1  1
26         2       1       4       2      1      1      2  1  2  2  2  4  2  2
27         2       2       2       2      1      1      2  4  2  2  3  3  2  2
28         2       1       2       1      1      1      1  2  2  1  1  1  3  1
29         2       2       2       2      1      1      1  4  4  4  1  1  2  2
...      ...     ...     ...     ...    ...    ...    ... .. .. .. .. .. .. ..
3719       2       3       4       4      4      4      4  1  4  4  4  4  4  4
3720       2       3       2       2      1      1      1  3  3  3  2  1  1  1
3721       2       3       2       3      1      1      3  3  3  3  3  3  3  3
3722       2       4       2       4      1      1      4  4  4  4  4  4  4  4
3723       4       4       4       4      4      4      4  4  4  4  4  2  4  4
3724       2       2       2       4      1      1      2  2  2  4  4  1  2  2
3725       2       4       2       4      1      1      4  4  4  4  4  4  4  4
3726       2       2       2       1      1      1      1  2  1  1  1  1  4  2
3727       2       3       2       4      1      1      4  3  3  4  2  2  4  4
3728       2       1       2       2      1      1      2  1  1  2  1  1  2  2
3729       4       2       4       4      1      1      1  2  2  2  4  1  1  1
3730       2       1       2       1      1      1      2  2  2  2  1  1  2  2
3731       2       2       2       2      1      1      4  2  2  2  2  2  2  2
3732       2       1       2       2      1      1      1  2  2  2  1  1  2  2
3733       3       4       2       3      1      1      3  3  3  3  3  3  3  3
3734       2       4       2       1      1      1      1  4  1  2  1  1  4  1
3735       2       2       2       3      2      2      3  3  3  3  3  3  3  3
3736       2       1       2       1      1      1      1  1  1  2  1  1  2  2
3737       2       2       2       2      1      1      2  2  2  2  2  2  2  2
3738       2       2       4       2      1      1      4  2  2  2  1  1  4  4
3739       2       1       2       1      1      1      4  2  2  2  1  2  2  4
3740       2       4       4       4      4      4      4  4  4  4  4  4  4  4
3741       2       3       2       3      1      1      4  3  3  2  3  3  3  3
3742       2       4       2       4      1      1      1  4  4  2  1  1  1  1
3743       4       4       4       4      4      4      4  4  4  4  4  4  4  4
3744       2       2       4       3      1      1      2  2  3  3  3  3  3  3
3745       2       4       2       3      1      1      1  1  1  2  1  1  4  1
3746       4       4       4       4      1      1      4  4  4  4  1  2  4  4
3747       2       2       2       2      1      1      2  2  2  2  3  3  3  3
3748       4       2       4       2      1      1      4  2  2  3  3  3  4  4

[3749 rows x 14 columns]

In [8]:
predict = result.mode(axis='columns')

In [9]:
predict

        0    1   2
0     4.0  NaN NaN
1     2.0  NaN NaN
2     2.0  NaN NaN
3     4.0  NaN NaN
4     1.0  NaN NaN
5     2.0  NaN NaN
6     2.0  NaN NaN
7     4.0  NaN NaN
8     1.0  NaN NaN
9     4.0  NaN NaN
10    4.0  NaN NaN
11    4.0  NaN NaN
12    4.0  NaN NaN
13    2.0  3.0 NaN
14    2.0  NaN NaN
15    2.0  NaN NaN
16    1.0  NaN NaN
17    1.0  3.0 NaN
18    1.0  NaN NaN
19    2.0  NaN NaN
20    2.0  NaN NaN
21    4.0  NaN NaN
22    2.0  NaN NaN
23    4.0  NaN NaN
24    2.0  NaN NaN
25    1.0  NaN NaN
26    2.0  NaN NaN
27    2.0  NaN NaN
28    1.0  NaN NaN
29    2.0  NaN NaN
...   ...  ...  ..
3719  4.0  NaN NaN
3720  1.0  NaN NaN
3721  3.0  NaN NaN
3722  4.0  NaN NaN
3723  4.0  NaN NaN
3724  2.0  NaN NaN
3725  4.0  NaN NaN
3726  1.0  NaN NaN
3727  4.0  NaN NaN
3728  1.0  2.0 NaN
3729  1.0  NaN NaN
3730  2.0  NaN NaN
3731  2.0  NaN NaN
3732  2.0  NaN NaN
3733  3.0  NaN NaN
3734  1.0  NaN NaN
3735  3.0  NaN NaN
3736  1.0  NaN NaN
3737  2.0  NaN NaN
3738  2.0  NaN NaN
3739  2.0  NaN NaN
3740  4.0  NaN NaN
3741  3.0  NaN NaN
3742  1.0  NaN NaN
3743  4.0  NaN NaN
3744  3.0  NaN NaN
3745  1.0  NaN NaN
3746  4.0  NaN NaN
3747  2.0  NaN NaN
3748  4.0  NaN NaN

[3749 rows x 3 columns]

In [10]:
index = 0
while index < predict.shape[0]:
    temp = predict[ math.floor(random.random()*predict.count(axis='columns')[0]) ][index]
    predict[0][index] = temp
    index+=1

In [11]:
from sklearn.model_selection import train_test_split
data=pd.read_csv(path+"\\data\\train.csv")
X = data
y = data['AdoptionSpeed']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [12]:
ans = pd.DataFrame([]) 
ans = pd.concat([ans, y_test], axis=1, ignore_index = True )
ans = ans.reset_index()[0]

In [13]:
def accuracy(pred,ans):
    count=0
    for i in range(len(pred)):
        if pred[i]==ans[i]:
            count+=1
    return count/len(pred)
accuracy(predict[0],ans)

0.41611096292344624

In [14]:
predict[0].to_csv(path+"\\result\\voting.csv", index=False)